# Generated by Django 5.1.6 on 2025-04-29 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_devicetoken_delete_jobseekerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='devicetoken',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='devicetoken',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtype',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_applicant'),
        ),
    ]
