# Generated by Django 5.1.6 on 2025-05-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobperiod',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='jobs.job'),
        ),
    ]
