# Generated by Django 5.1.6 on 2025-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobperiod_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobPeriod',
        ),
    ]
