# Generated by Django 5.1.6 on 2025-06-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_activity_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
