# Generated by Django 5.1.6 on 2025-06-04 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_cv_skills_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dt3k9eyfz/image/upload/v1748975047/qvrmont4ahizqkxvum6m.png', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
