# Generated by Django 5.1.6 on 2025-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtype_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='cv/%Y/%m'),
        ),
    ]
