# Generated by Django 5.1.6 on 2025-04-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_options_alter_jobtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSaveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='jobs.cv')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.recruiterprofile')),
            ],
            options={
                'unique_together': {('cv', 'recruiter')},
            },
        ),
        migrations.CreateModel(
            name='CVView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.cv')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.recruiterprofile')),
            ],
            options={
                'unique_together': {('cv', 'viewer')},
            },
        ),
    ]
